Add integration-test config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,115 +1,88 @@
-default_filters: &default_filters
-  branches:
-    only: /.*/
-  tags:
-    only: /.*/
-
 version: 2.1
 
 orbs:
   cli: circleci/circleci-cli@0.1.5
 
 jobs:
-  validation:
-    executor: cli/default
-    steps:
-      - cli/install
-      - checkout
-      - run:
-          name: バリデーション
-          command: circleci orb validate ./src/orb.yml
-
-  expansion:
-    executor: cli/default
-    steps:
-      - cli/install
-      - checkout
-      - run:
-          name: Install yq
-          command: |
-            sudo apt update && \
-            sudo apt-get install jq python-pip python-dev && \
-            sudo pip install yq
-      - run:
-          name: 展開テスト
-          command: |
-            result=$(circleci config process .circleci/test.yml | yq '.jobs."hello-world/echo-job".steps[0].run.command')
-            echo ${result} | grep "Hello, CircleCI"
-
-  execution:
-      machine: true
+    integration-test:
+      executor: cli/default
       steps:
-        - cli/install
         - checkout
-        - run:
-            name: 展開
-            command: circleci config process .circleci/test.yml > .circleci/2.0.yml
-        - run:
-            name: ランタイムテスト
-            command: circleci local execute --config .circleci/2.0.yml --job hello-world/echo-job | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"
 
-  publish-dev:
-    executor: cli/default
-    steps:
-      - cli/install
-      - checkout
-      - run:
-          name: dev:alphaを公開
-          command: circleci orb publish src/orb.yml sample-orbs/hello-world@dev:alpha --token ${CIRCLE_TOKEN}
+        - cli/install
+        - run:
+            name: セットアップ
+            command: |
+              echo 'export BRANCH=INTEGRATION_TEST/${CIRCLE_SHA1}' >> $BASH_ENV
+              echo 'export TEST_REPOSITORY=hello-world-integration-test' >> $BASH_ENV
+              echo 'export TEST_REPOSITORY_USER=circleci-book' >> $BASH_ENV
+              echo 'export ORB_REF=sample-orbs/hello-world@dev:${CIRCLE_SHA1}' >> $BASH_ENV
 
-  dev-promote-prod:
-    parameters:
-      release:
-        type: enum
-        enum: [patch, minor, major]
-        default: patch
-        description: circleci orb publish promoteコマンドの引数
-    executor: cli/default
-    steps:
-      - cli/install
-      - checkout
-      - run:
-          name: dev:alphaを本番用Orbsへプロモートする
-          command: circleci orb publish promote sample-orbs/hello-world@dev:alpha << parameters.release >> --token ${CIRCLE_TOKEN}
+              git config --global user.email "circleci@example.com"
+              git config --global user.name "CircleCI"
+
+        - add_ssh_keys:
+            fingerprints:
+              - "<フィンガープリント>"
+
+        - run:
+            name: 開発用Orbをパブリッシュ
+            command: circleci orb publish ./src/orb.yml ${ORB_REF} --token ${CIRCLE_TOKEN}
+
+        - run:
+            name: 直前にパブリッシュした開発用Orbを使って、別リポジトリのビルドを開始する
+            command: |
+              git clone git@github.com:TEST_REPOSITORY_USER/${TEST_REPOSITORY}.git
+              cd ${TEST_REPOSITORY}
+              git checkout -b ${BRANCH}
+              mkdir -p .circleci
+              cat \<<EOF > .circleci/config.yml
+                version: 2.1
+                orbs:
+                  hello-world: ${ORB_REF}
+                workflows:
+                  hello-workflow:
+                    jobs:
+                      - hello-world/echo-job:
+                          to: CircleCI
+              EOF
+              git add .
+              git commit -m "Updates from ${CIRCLE_BUILD_URL}"
+              git push -f --set-upstream origin ${BRANCH}
+
+        - run:
+            name: ビルドが完了するまで問い合わせる
+            command: |
+              while true; do
+                curl "https://circleci.com/api/v1.1/project/github/TEST_REPOSITORY_USER/${TEST_REPOSITORY}/tree/${BRANCH}?circle-token=${CIRCLE_TOKEN}&limit=1&filter=completed" > build-result.json
+
+                STOP_TIME=$(cat build-result.json | jq -r '.[0].stop_time')
+                if [ "$STOP_TIME" != "null" ]; then
+                  break
+                fi
+
+
+                sleep 15
+              done
+
+              STATUS=$(cat build-result.json | jq -r '.[0].status')
+              if [ "$STATUS" == "success" ];then
+                echo "GitHub Integration Test Succeeded"
+                exit 0
+              else
+                echo "GitHub Integration Test Failed"
+                exit 1
+              fi
+
+        - run:
+            when: always
+            working_directory: hello-world-integration-test
+            name: テスト用のブランチを削除する
+            command: |
+              git push origin --delete ${BRANCH}
 
 workflows:
+  version: 2
   main:
     jobs:
-      - validation:
-          filters:
-            *default_filters
-      - publish-dev:
-          filters:
-            *default_filters
-      - expansion:
-          requires: [publish-dev]
-          filters:
-            *default_filters
-      - execution:
-          requires: [publish-dev]
-          filters:
-            *default_filters
-      - dev-promote-prod:
-          requires: [validation, expansion, execution]
-          filters:
-            branches:
-              ignore: /.*/
-            tags:
-              only: /patch.*/
-          release: patch
-      - dev-promote-prod:
-          requires: [validation, expansion, execution]
-          filters:
-            branches:
-              ignore: /.*/
-            tags:
-              only: /minor.*/
-          release: minor
-      - dev-promote-prod:
-          requires: [validation, expansion, execution]
-          filters:
-            branches:
-              ignore: /.*/
-            tags:
-              only: /major.*/
-          release: major
+      - integration-test
